---
title: "Northern Forest"
output: html_document
---

Packages 

```{r}
#library(SDMTools)
library(raster)
library(rgdal)
library(maptools)
library(sp)
library(adehabitatHR)
library(dplyr)
library(plyr)
library(landscapemetrics)
setwd("E:/Northern_forest/")


panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- abs(cor(x, y))
    txt <- format(c(r, 0.123456789), digits = digits)[1]
    txt <- paste0(prefix, txt)
    if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt, cex = 2)
}
```

Packages 
```{r}
# data ####


raster <- raster("tif1.tif", crs = 27700) # import rasterized NFI woodland cover data
plot(raster)
raster[raster[] == 2] <- 1 

GRID <- readOGR(dsn=".", layer="grids")
plot(GRID)
proj4string(GRID)
proj4string(raster)
image(raster)
plot(GRID, add=T)

indata <- GRID
innames <- unique(GRID@data$TILE_NAME)
outnames <- innames

# begin loop to create separate grid shapefiles for each TILE_NAME
for (i in 1:length(innames)){
  data <- indata[which(indata$TILE_NAME==innames[i]),]
  if(dim(data)[1] != 0){
    writePolyShape(data,fn=paste(outnames[i],sep="/"),factor2char=TRUE)
    write.table(innames, "List.txt", eol=".shp\n", col.names=FALSE, quote=FALSE, row.names=FALSE)
  }}

#Read in a list of shapefiles files from above
Listshps<-read.table("List.txt",sep="\t",header=F)


#Now we use the plyr package to create a single function that runs multiple functions in a single statement.
# function ####
shape <- function(Listshps) {
  file <- as.character(Listshps[1,])
  shape <-readShapeSpatial(file)
  clipped <- crop(raster, shape) #clip raster for shape
  ### Calculate the Class statistics in each grid
  grid.data <- calculate_lsm(clipped, level = "class")
}

NAs <- function(Listshps) {
  file <- as.character(Listshps[1,])
  shape <-readShapeSpatial(file)
  clipped <- crop(raster, shape) #clip raster for shape
  ### Calculate the Class statistics in each grid
  grid.data <- freq(clipped)
}
#Now we use the plyr package to create a single function that runs multiple functions in a single statement.


#The line below also uses the plyr package to run the newly created function (shape) over the list of shapefiles called in with the List statement (Listshps) by each ID ([.(id)]) in the Listshps
# data ####
results <- ddply(Listshps, .(V1), shape)
NAs_land <- ddply(Listshps, .(V1), NAs)
write.table(results, "fragstats_class_all.txt")
write.table(NAs_land, "fragstats_NAs_land.txt")

results_sub <- subset(results, results$class == 1)
library(stringr)

results_sub$V1 <- str_sub(results_sub$V1,1,nchar(results_sub$V1)-4) 
results_sub <- subset(results_sub, select = c("V1","metric","value"))

results_sub %>%
  reshape(
    idvar = "V1",
    timevar = "metric",
    direction = "wide"
  ) -> Subset
write.csv(Subset, "data_subset.csv") # dave data with all fragsrars


```


# data analaysis

```{r}
#stats ####      
# data <- read.csv("data_subset.csv", header = T)



dotchart(data$pland)   
hist(data$ca, breaks = 40, xlab = "Woodland cover (Ha)")
hist(data$pland, breaks = 40, xlab = "Percentage of woodlands")
hist(data$np, breaks = 40, xlab = "Number of patches")
hist(data$pd, breaks = 40, xlab = "Patch density")
hist(data$area_mn, breaks = 40, xlab = "Mean patch size (Ha)")
hist(data$cohesion, breaks = 40, xlab = "cohesion")
hist(data$clumpy, breaks = 40, xlab = "clumpy")
hist(data$contig_mn, breaks = 40, xlab = "contig")


range(data$ca)
range(data$pland)
range(data$np)
range(data$pd)
range(data$area_mn)
range(data$cohesion)
range(data$clumpy)
range(data$contig_mn)


mean(data$ca)
mean(data$pland)
mean(data$np)
mean(data$pd)
mean(data$area_mn)
mean(data$cohesion)
mean(data$clumpy)
mean(data$contig_mn)

sd(data$ca)/ sqrt(1115)
sd(data$pland) / sqrt(1115)
sd(data$np) / sqrt(1115)
sd(data$pd) / sqrt(1115)
sd(data$area_mn) / sqrt(1115)
sd(data$cohesion) / sqrt(1115)
sd(data$clumpy) / sqrt(1115)
sd(data$contig_mn) / sqrt(1115)


#data <- read.csv("data_subset.csv", header = T)
library(corrplot)
library(RColorBrewer)

data_tree <-  dplyr::rename(data, 
                            Woodland_Ha = ca,
                            Woodland_percent = pland,
                            Number_patches = np,
                            patch_density = pd,
                            mean_patch_area = area_mn)
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y))
  txt <- format(c(r, 0.123456789), digits = digits)[1]
  txt <- paste0(prefix, txt)
  if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
  text(0.5, 0.5, txt, cex = 2)
}


pairs(~ ca + pland + np + area_mn + cohesion + clumpy + contig_mn, upper.panel = panel.cor, data = data)


pairs(~ Woodland_Ha + Woodland_percent + Number_patches + mean_patch_area + cohesion + clumpy + contig_mn, upper.panel = panel.cor, data = data_tree)


```


# # sampling ####

```{r}
# # sampling ####
#before stratifying need to remove coastal squares 
data$percent <- (data$pland / 100) * 2500 #calculate how much area would be if no NAs 
data_sub <- subset(data, data$ca== data$percent) #remove coastal


testgroup <- slice_sample(data_sub, n = 100, weight_by = area_mn)
par(mfrow=c(2,6))
hist(testgroup$ca, breaks = 40, xlab = "Woodland cover (Ha)", xlim = c(min(data$ca), max(data$ca)))
hist(testgroup$np, breaks = 40, xlab = "Number of patches", xlim = c(min(data$np), max(data$np)))
hist(testgroup$area_mn, breaks = 40, xlab = "Mean patch size (Ha)", xlim = c(min(data$area_mn), max(data$area_mn)))
hist(testgroup$cohesion, breaks = 40, xlab = "cohesion", xlim = c(min(data$cohesion), max(data$cohesion)))
hist(testgroup$clumpy, breaks = 40, xlab = "clumpy", xlim = c(min(data$clumpy), max(data$clumpy)))
hist(testgroup$contig_mn, breaks = 40, xlab = "contig", xlim = c(min(data$contig_mn), max(data$contig_mn)))
hist(data$ca, breaks = 40, xlab = "Woodland cover (Ha)", xlim = c(min(data$ca), max(data$ca)))
hist(data$np, breaks = 40, xlab = "Number of patches", xlim = c(min(data$np), max(data$np)))
hist(data$area_mn, breaks = 40, xlab = "Mean patch size (Ha)", xlim = c(min(data$area_mn), max(data$area_mn)))
hist(data$cohesion, breaks = 40, xlab = "cohesion", xlim = c(min(data$cohesion), max(data$cohesion)))
hist(data$clumpy, breaks = 40, xlab = "clumpy", xlim = c(min(data$clumpy), max(data$clumpy)))
hist(data$contig_mn, breaks = 40, xlab = "contig", xlim = c(min(data$contig_mn), max(data$contig_mn)))




testgroup_cor <-  dplyr::rename(testgroup, 
                            Woodland_Ha = ca,
                            Woodland_percent = pland,
                            Number_patches = np,
                            patch_density = pd,
                            mean_patch_area = area_mn)

pairs(~ Woodland_Ha + Woodland_percent + Number_patches + mean_patch_area + cohesion + clumpy + contig_mn, upper.panel = panel.cor, data = testgroup_cor)



# plot sample squares ####
par(mfrow=c(1,1))
 plot(GRID)
 r <- testgroup$TILE_NAME
GRID_sub <- GRID
GRID_sub <- GRID_sub[GRID_sub$TILE_NAME %in% r,]
plot(GRID_sub)
writeOGR(GRID_sub, dsn=".", layer="sample_squares", driver="ESRI Shapefile") 
```

```{r}
#write.csv(data_sub, "E:/Northern_forest_ewan/sample_squares.csv")

```

```{r}

samples <- read.csv("E:/NorthernForestSamples/Samples.csv", header = T) #read in list of samples

data %>% filter(TILE_NAME %in% samples$TILE_NAME)-> sampled # subset landscape data jut to samples

```




# PCA analyisis 
```{r}


Landscape_pca <- sampled[ , -c(1)] #remove ID col

pca <- prcomp(formula = ~., data=Landscape_pca, center = TRUE, scale = TRUE, na.action = na.omit)

library("factoextra")
eig <- get_eigenvalue(pca)

var <- get_pca_var(pca)
var
head(var$coord, 4)
library("corrplot")
library(vegan)

fviz_eig(pca, addlabels = TRUE, ylim = c(0, 50))

?fviz_eig

fviz_pca_var(pca, axes = c(1, 2), col.var = "black")
corrplot(var$cos2, is.corr=FALSE)
fviz_cos2(pca, choice = "var", axes = 1)
axes <- as.data.frame(predict(pca, newdata = Landscape))
head(axes, 4)
library(fragstats)
lsm_abbreviations_names()
axes <- axes[ , c(1:5)]
Updated_land <- cbind(Landscape, axes)
write.csv(Updated_land, "C:/FionaPlenderleith/CH4_models/Analysis/Updated_land_PCA.csv") # write data

table <- as.data.frame(var[["contrib"]])
write.csv(table, "C:/FionaPlenderleith/CH4_models/Analysis/contribution.csv") #write data 




```

